// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(MoneyWizardContext))]
    [Migration("20260510174529_AddExceptionInsertions")]
    partial class AddExceptionInsertions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.ArgentinaUserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EmploymentStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("MonotributoCategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MonotributoCategoryId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ArgentinaUserProfiles");
                });

            modelBuilder.Entity("Domain.Models.ExpenseCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ExpenseCategories");
                });

            modelBuilder.Entity("Domain.Models.ExpenseException", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateOnly?>("OriginalDate")
                        .HasColumnType("date");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId", "Date")
                        .IsUnique()
                        .HasFilter("\"OriginalDate\" IS NULL");

                    b.HasIndex("SeriesId", "OriginalDate")
                        .IsUnique()
                        .HasFilter("\"OriginalDate\" IS NOT NULL");

                    b.ToTable("ExpenseExceptions", t =>
                        {
                            t.HasCheckConstraint("chk_expense_exception_isdeleted_only_on_override", "\"OriginalDate\" IS NOT NULL OR \"IsDeleted\" = FALSE");

                            t.HasCheckConstraint("chk_expense_exception_overlay_kind", "\"OriginalDate\" IS NOT NULL OR (\"Date\" IS NOT NULL AND \"Amount\" IS NOT NULL AND \"Currency\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Domain.Models.ExpenseSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<Guid?>("InvoiceSeriesId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PaycheckSeriesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceSeriesId");

                    b.HasIndex("PaycheckSeriesId");

                    b.HasIndex("SeriesId", "EffectiveFrom")
                        .IsUnique();

                    b.ToTable("ExpenseSegments");
                });

            modelBuilder.Entity("Domain.Models.ExpenseSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("ExpenseSeries");
                });

            modelBuilder.Entity("Domain.Models.Investment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssetClass")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("ManualYield")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<string>("Ticker")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Investments");
                });

            modelBuilder.Entity("Domain.Models.InvoiceCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Bottom")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateOnly>("CutDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Tax")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Top")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("InvoiceCategories");
                });

            modelBuilder.Entity("Domain.Models.InvoiceException", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<long?>("Number")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("OriginalDate")
                        .HasColumnType("date");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId", "Date")
                        .IsUnique()
                        .HasFilter("\"OriginalDate\" IS NULL");

                    b.HasIndex("SeriesId", "OriginalDate")
                        .IsUnique()
                        .HasFilter("\"OriginalDate\" IS NOT NULL");

                    b.ToTable("InvoiceExceptions", t =>
                        {
                            t.HasCheckConstraint("chk_invoice_exception_isdeleted_only_on_override", "\"OriginalDate\" IS NOT NULL OR \"IsDeleted\" = FALSE");

                            t.HasCheckConstraint("chk_invoice_exception_overlay_kind", "\"OriginalDate\" IS NOT NULL OR (\"Date\" IS NOT NULL AND \"Amount\" IS NOT NULL AND \"Currency\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Domain.Models.InvoiceSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Source")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Source");

                    b.HasIndex("SeriesId", "EffectiveFrom")
                        .IsUnique();

                    b.ToTable("InvoiceSegments");
                });

            modelBuilder.Entity("Domain.Models.InvoiceSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("BaseNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("Class")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("ParentExceptionId")
                        .HasColumnType("uuid");

                    b.Property<int?>("PointOfSale")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasDefaultValue("Invoice");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentExceptionId")
                        .HasFilter("\"ParentExceptionId\" IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("InvoiceSeries");
                });

            modelBuilder.Entity("Domain.Models.PaycheckException", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateOnly?>("OriginalDate")
                        .HasColumnType("date");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId", "Date")
                        .IsUnique()
                        .HasFilter("\"OriginalDate\" IS NULL");

                    b.HasIndex("SeriesId", "OriginalDate")
                        .IsUnique()
                        .HasFilter("\"OriginalDate\" IS NOT NULL");

                    b.ToTable("PaycheckExceptions", t =>
                        {
                            t.HasCheckConstraint("chk_paycheck_exception_isdeleted_only_on_override", "\"OriginalDate\" IS NOT NULL OR \"IsDeleted\" = FALSE");

                            t.HasCheckConstraint("chk_paycheck_exception_overlay_kind", "\"OriginalDate\" IS NOT NULL OR (\"Date\" IS NOT NULL AND \"Amount\" IS NOT NULL AND \"Currency\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Domain.Models.PaycheckSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId", "EffectiveFrom")
                        .IsUnique();

                    b.ToTable("PaycheckSegments");
                });

            modelBuilder.Entity("Domain.Models.PaycheckSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PaycheckSeries");
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Country")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasDefaultValue("row");

                    b.Property<DateOnly>("Dob")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Models.ArgentinaUserProfile", b =>
                {
                    b.HasOne("Domain.Models.InvoiceCategory", "MonotributoCategory")
                        .WithMany()
                        .HasForeignKey("MonotributoCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Models.User", "User")
                        .WithOne("ArgentinaProfile")
                        .HasForeignKey("Domain.Models.ArgentinaUserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonotributoCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.ExpenseCategory", b =>
                {
                    b.HasOne("Domain.Models.User", "User")
                        .WithMany("ExpenseCategories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.ExpenseException", b =>
                {
                    b.HasOne("Domain.Models.ExpenseSeries", "Series")
                        .WithMany("Exceptions")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Domain.Models.ExpenseSegment", b =>
                {
                    b.HasOne("Domain.Models.InvoiceSeries", "InvoiceSeries")
                        .WithMany()
                        .HasForeignKey("InvoiceSeriesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Models.PaycheckSeries", "PaycheckSeries")
                        .WithMany()
                        .HasForeignKey("PaycheckSeriesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Models.ExpenseSeries", "Series")
                        .WithMany("Segments")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.Models.RecurrenceRule", "RecurrenceRule", b1 =>
                        {
                            b1.Property<Guid>("ExpenseSegmentId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly?>("EndDate")
                                .HasColumnType("date")
                                .HasColumnName("RecurrenceEndDate");

                            b1.Property<int>("Frequency")
                                .HasColumnType("integer")
                                .HasColumnName("RecurrenceFrequency");

                            b1.Property<int>("Interval")
                                .HasColumnType("integer")
                                .HasColumnName("RecurrenceInterval");

                            b1.Property<int?>("TotalInstallments")
                                .HasColumnType("integer")
                                .HasColumnName("RecurrenceTotalInstallments");

                            b1.HasKey("ExpenseSegmentId");

                            b1.ToTable("ExpenseSegments");

                            b1.WithOwner()
                                .HasForeignKey("ExpenseSegmentId");
                        });

                    b.Navigation("InvoiceSeries");

                    b.Navigation("PaycheckSeries");

                    b.Navigation("RecurrenceRule");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Domain.Models.ExpenseSeries", b =>
                {
                    b.HasOne("Domain.Models.ExpenseCategory", "Category")
                        .WithMany("ExpenseSeries")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Models.User", "User")
                        .WithMany("ExpenseSeries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.Investment", b =>
                {
                    b.HasOne("Domain.Models.User", "User")
                        .WithMany("Investments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.InvoiceException", b =>
                {
                    b.HasOne("Domain.Models.InvoiceSeries", "Series")
                        .WithMany("Exceptions")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Domain.Models.InvoiceSegment", b =>
                {
                    b.HasOne("Domain.Models.InvoiceSeries", "Series")
                        .WithMany("Segments")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.PaycheckSeries", "PaycheckSeries")
                        .WithMany()
                        .HasForeignKey("Source")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("Domain.Models.RecurrenceRule", "RecurrenceRule", b1 =>
                        {
                            b1.Property<Guid>("InvoiceSegmentId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly?>("EndDate")
                                .HasColumnType("date")
                                .HasColumnName("RecurrenceEndDate");

                            b1.Property<int>("Frequency")
                                .HasColumnType("integer")
                                .HasColumnName("RecurrenceFrequency");

                            b1.Property<int>("Interval")
                                .HasColumnType("integer")
                                .HasColumnName("RecurrenceInterval");

                            b1.Property<int?>("TotalInstallments")
                                .HasColumnType("integer")
                                .HasColumnName("RecurrenceTotalInstallments");

                            b1.HasKey("InvoiceSegmentId");

                            b1.ToTable("InvoiceSegments");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceSegmentId");
                        });

                    b.Navigation("PaycheckSeries");

                    b.Navigation("RecurrenceRule");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Domain.Models.InvoiceSeries", b =>
                {
                    b.HasOne("Domain.Models.InvoiceException", "ParentException")
                        .WithMany("ChildSeries")
                        .HasForeignKey("ParentExceptionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Models.User", "User")
                        .WithMany("InvoiceSeries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentException");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.PaycheckException", b =>
                {
                    b.HasOne("Domain.Models.PaycheckSeries", "Series")
                        .WithMany("Exceptions")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Domain.Models.PaycheckSegment", b =>
                {
                    b.HasOne("Domain.Models.PaycheckSeries", "Series")
                        .WithMany("Segments")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.Models.RecurrenceRule", "RecurrenceRule", b1 =>
                        {
                            b1.Property<Guid>("PaycheckSegmentId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly?>("EndDate")
                                .HasColumnType("date")
                                .HasColumnName("RecurrenceEndDate");

                            b1.Property<int>("Frequency")
                                .HasColumnType("integer")
                                .HasColumnName("RecurrenceFrequency");

                            b1.Property<int>("Interval")
                                .HasColumnType("integer")
                                .HasColumnName("RecurrenceInterval");

                            b1.Property<int?>("TotalInstallments")
                                .HasColumnType("integer")
                                .HasColumnName("RecurrenceTotalInstallments");

                            b1.HasKey("PaycheckSegmentId");

                            b1.ToTable("PaycheckSegments");

                            b1.WithOwner()
                                .HasForeignKey("PaycheckSegmentId");
                        });

                    b.Navigation("RecurrenceRule");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Domain.Models.PaycheckSeries", b =>
                {
                    b.HasOne("Domain.Models.User", "User")
                        .WithMany("PaycheckSeries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.ExpenseCategory", b =>
                {
                    b.Navigation("ExpenseSeries");
                });

            modelBuilder.Entity("Domain.Models.ExpenseSeries", b =>
                {
                    b.Navigation("Exceptions");

                    b.Navigation("Segments");
                });

            modelBuilder.Entity("Domain.Models.InvoiceException", b =>
                {
                    b.Navigation("ChildSeries");
                });

            modelBuilder.Entity("Domain.Models.InvoiceSeries", b =>
                {
                    b.Navigation("Exceptions");

                    b.Navigation("Segments");
                });

            modelBuilder.Entity("Domain.Models.PaycheckSeries", b =>
                {
                    b.Navigation("Exceptions");

                    b.Navigation("Segments");
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Navigation("ArgentinaProfile");

                    b.Navigation("ExpenseCategories");

                    b.Navigation("ExpenseSeries");

                    b.Navigation("Investments");

                    b.Navigation("InvoiceSeries");

                    b.Navigation("PaycheckSeries");
                });
#pragma warning restore 612, 618
        }
    }
}
