// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(MoneyWizardContext))]
    [Migration("20260406205929_AddRecurrenceSupport")]
    partial class AddRecurrenceSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateOnly?>("OriginalDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("RecurringExpenseId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Source")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Source");

                    b.HasIndex("UserId");

                    b.HasIndex("RecurringExpenseId", "OriginalDate")
                        .IsUnique()
                        .HasFilter("\"RecurringExpenseId\" IS NOT NULL");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("Domain.Models.ExpenseCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ExpenseCategories");
                });

            modelBuilder.Entity("Domain.Models.Paycheck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateOnly?>("OriginalDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("RecurringPaycheckId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("RecurringPaycheckId", "OriginalDate")
                        .IsUnique()
                        .HasFilter("\"RecurringPaycheckId\" IS NOT NULL");

                    b.ToTable("Paychecks");
                });

            modelBuilder.Entity("Domain.Models.PaycheckDistribution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("Source")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Source");

                    b.ToTable("PaycheckDistributions");
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Dob")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Models.Expense", b =>
                {
                    b.HasOne("Domain.Models.ExpenseCategory", "Category")
                        .WithMany("Expenses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Models.Expense", "RecurringExpense")
                        .WithMany("Exceptions")
                        .HasForeignKey("RecurringExpenseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Models.Paycheck", "Paycheck")
                        .WithMany("Expenses")
                        .HasForeignKey("Source")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Models.User", "User")
                        .WithMany("Expenses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.Models.RecurrenceRule", "RecurrenceRule", b1 =>
                        {
                            b1.Property<Guid>("ExpenseId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly?>("EndDate")
                                .HasColumnType("date")
                                .HasColumnName("RecurrenceEndDate");

                            b1.Property<int>("Frequency")
                                .HasColumnType("integer")
                                .HasColumnName("RecurrenceFrequency");

                            b1.Property<int>("Interval")
                                .HasColumnType("integer")
                                .HasColumnName("RecurrenceInterval");

                            b1.Property<int?>("TotalInstallments")
                                .HasColumnType("integer")
                                .HasColumnName("RecurrenceTotalInstallments");

                            b1.HasKey("ExpenseId");

                            b1.ToTable("Expenses");

                            b1.WithOwner()
                                .HasForeignKey("ExpenseId");
                        });

                    b.Navigation("Category");

                    b.Navigation("Paycheck");

                    b.Navigation("RecurrenceRule");

                    b.Navigation("RecurringExpense");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.ExpenseCategory", b =>
                {
                    b.HasOne("Domain.Models.User", "User")
                        .WithMany("ExpenseCategories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.Paycheck", b =>
                {
                    b.HasOne("Domain.Models.Paycheck", "RecurringPaycheck")
                        .WithMany("Exceptions")
                        .HasForeignKey("RecurringPaycheckId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Models.User", "User")
                        .WithMany("Paychecks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.Models.RecurrenceRule", "RecurrenceRule", b1 =>
                        {
                            b1.Property<Guid>("PaycheckId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly?>("EndDate")
                                .HasColumnType("date")
                                .HasColumnName("RecurrenceEndDate");

                            b1.Property<int>("Frequency")
                                .HasColumnType("integer")
                                .HasColumnName("RecurrenceFrequency");

                            b1.Property<int>("Interval")
                                .HasColumnType("integer")
                                .HasColumnName("RecurrenceInterval");

                            b1.Property<int?>("TotalInstallments")
                                .HasColumnType("integer")
                                .HasColumnName("RecurrenceTotalInstallments");

                            b1.HasKey("PaycheckId");

                            b1.ToTable("Paychecks");

                            b1.WithOwner()
                                .HasForeignKey("PaycheckId");
                        });

                    b.Navigation("RecurrenceRule");

                    b.Navigation("RecurringPaycheck");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.PaycheckDistribution", b =>
                {
                    b.HasOne("Domain.Models.Paycheck", "Paycheck")
                        .WithMany("Distributions")
                        .HasForeignKey("Source")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Paycheck");
                });

            modelBuilder.Entity("Domain.Models.Expense", b =>
                {
                    b.Navigation("Exceptions");
                });

            modelBuilder.Entity("Domain.Models.ExpenseCategory", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("Domain.Models.Paycheck", b =>
                {
                    b.Navigation("Distributions");

                    b.Navigation("Exceptions");

                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Navigation("ExpenseCategories");

                    b.Navigation("Expenses");

                    b.Navigation("Paychecks");
                });
#pragma warning restore 612, 618
        }
    }
}
